theme: jekyll-theme-cayman
title: Hello, I am Audric Wannaz. You landed on my page, welcome!
description: Here, you will find information on my academik work on Ancient History and Digital Humanities
