theme: jekyll-theme-cayman
title: Welcome to Audric Wannaz's Github page!
description: Here you can find some infos on me as well as notebooks related to my work on Ancient History and Digital Humanities
